### ISSUE TITLE
It crashes when I try to run the sample code

### ISSUE THREAD

**Issue by simnalamburt** [disjukr/electrun#1]
##### [Project Link](https://github.com/simnalamburt/hyperlink-validator)

``` bash
$ git clone https://github.com/simnalamburt/hyperlink-validator.git --depth=1
$ cd hyperlink-validator
$ npm install

# ...

$ npm test
No errors!
$ ./run
ello, electrun!
```

![2016-04-11 3 31 22](https://cloud.githubusercontent.com/assets/4435445/14412128/10e9c57c-ff96-11e5-8f73-68a6dd2554dc.png)

**Comment by disjukr** [comment]
fixed in https://github.com/disjukr/electrun/commit/9d0e2db3b29b6489eae64eac95d69d512dcb2d7a
